### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by ranhsd** [ARozar/multer-google-storage#9]
Hi, 
In google cloud storage NodeJS module there is an option to mark files as **public**
It's part of the createWriteStream function. 
Marking files public will expose them to the internet. The default is that all files are not public and if someone will try to access to file URL he will get access denied error

Wanted to ask if there is an option to add the ability to mark files as public? 

Thanks.

**Comment by ranhsd** [comment]
Fixed! You only need to send 'publicread' in the acl parameter

**Comment by mvillaizan** [comment]
No matter how I configure it I always get:

Cannot use ACL API to set object policy when object policies are disabled.

```
var multerGoogleCloudStorage = require('multer-google-storage');
storage = multerGoogleCloudStorage.storageEngine({
	projectId: configuration.SE.GCP.projectId,
	keyFilename: configuration.SE.GCP.keyFilename,
	bucket: configuration.SE.GCP.storage.buckets.answers,
	filename: function (req, file, cb) {
		cb(null, file.originalname);
	}
});
```

Any ideas?

**Comment by JohnnyChien** [comment]
> No matter how I configure it I always get:
> 
> Cannot use ACL API to set object policy when object policies are disabled.
> 
> ```
> var multerGoogleCloudStorage = require('multer-google-storage');
> storage = multerGoogleCloudStorage.storageEngine({
> 	projectId: configuration.SE.GCP.projectId,
> 	keyFilename: configuration.SE.GCP.keyFilename,
> 	bucket: configuration.SE.GCP.storage.buckets.answers,
> 	filename: function (req, file, cb) {
> 		cb(null, file.originalname);
> 	}
> });
> ```
> 
> Any ideas?

I think this is because you have your bucket set to 'Bucket Policy Only'. You can check this by going to the bucket browser and see the column, named "Access control model" for the bucket you are working with.

<img width="1243" alt="Storage Browser" src="https://user-images.githubusercontent.com/1250856/64478090-fbe59d80-d157-11e9-9d2d-3cb197544310.png">

To update the bucket policy, either you can go into the bucket and click Edit Bucket on the top or go to the Permission tab inside of the bucket page. 

<img width="1021" alt="Update Bucket Screen" src="https://user-images.githubusercontent.com/1250856/64478098-27688800-d158-11e9-981b-294e450ec672.png">

If this a new project, simply create a new bucket and make sure the access control model is not Bucket Policy Only.

<img width="834" alt="Screen Shot 2019-09-07 at 10 11 18 AM" src="https://user-images.githubusercontent.com/1250856/64478115-68609c80-d158-11e9-9297-1a727a53d93e.png">
